permalink: /discover/:year/:month/:day/:title.html

xcsoar_stable_version: 6.1.3
xcsoar_testing_version: 6.2_alpha1
xcsoar_old_version: 6.0.10

xcsoar_next_milestone: 'XCSoar 6.2'

download_server_url: 'http://download.xcsoar.org/releases/'
