permalink: /discover/:year/:month/:day/:title.html

xcsoar_stable_version: 6.4.4
xcsoar_testing_version: 6.4.4
xcsoar_old_version: 6.3.11

xcsoar_next_milestone: 'XCSoar 6.5'

server_url: 'http://www.xcsoar.org'
download_server_url: 'http://download.xcsoar.org/releases'

asset_bundler:
  cdn: 'http://www.xcsoar.org'
  compress:
    css: 'yui-compressor --type css'
    js: 'yui-compressor --type js'
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'> </script>\n"
