permalink: /discover/:year/:month/:day/:title.html

xcsoar_stable_version: 6.6
xcsoar_testing_version: 6.6_beta2
xcsoar_old_version: 6.5.4

xcsoar_next_milestone: 'XCSoar 6.7'

server_url: ''
absolute_server_url: 'http://www.xcsoar.org'
download_server_url: 'http://download.xcsoar.org/releases'
trac_server_url: 'http://bugs.xcsoar.org'

asset_bundler:
  cdn: 'http://www.xcsoar.org'
  compress:
    css: 'yui-compressor --type css'
    js: 'yui-compressor --type js'
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'> </script>\n"
