permalink: /discover/:year/:month/:day/:title.html

xcsoar_stable_version: 6.3.10
xcsoar_testing_version: 6.4_beta1
xcsoar_old_version: 6.2.6

xcsoar_next_milestone: 'XCSoar 6.4'

download_server_url: 'http://download.xcsoar.org/releases/'
